name: On Push (main)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo event data
        run: |
          echo "github.event.head_commit.message: ${{ github.event.head_commit.message }}"

      - name: Completed run
        run: exit 0
