name: On release
on:
  release:
    types: [released]

jobs:
  release_job:
    if: github.event.release.target_commitish == 'main'
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo event data
        run: |
          echo "github.event.release.target_commitish: ${{ github.event.release.target_commitish }}"
          echo "github.event.release.name: ${{ github.event.release.name }}"
          echo "github.event.release.tag_name: ${{ github.event.release.tag_name }}"

      - name: 'Fake release of: ${{ github.event.release.tag_name }} @ ${{ github.event.release.target_commitish }}'
        run: exit 0
